# 小作業
# 1~100之間的亂數
# 1~200的List 使用shuffle 幫我打亂
# 設定seed使得每次shuffle都一樣

In [9]:
import numpy as np
np.random.randint(1,100)

65

In [12]:
arr = np.arange(1,201)
print(arr)
np.random.shuffle(arr)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200]
[ 96  57  60  80   2 113  53  13 176 146  54 188  40 152 101  64 185 106
 197   1 147 124  26 129  46 112 149  75  72  74 192 140 186 131 123   5
 109  52  45 175  21 168  63 119  37 134 

In [19]:
arr = np.arange(1,201)
print(arr)
np.random.seed(42)
np.random.shuffle(arr)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200]
[ 96  16  31 159 129 116  70 171 175  46  67 183 166  79 187 178  57 153
  83  69 125  17 149  94  66  61  85  68 126 133  10  19  56  76 151 105
 136 138 165  77  80 198  39  25 123 196 

In [21]:
arra = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(ranarr)

[37 23  4 33  5 21 10 47 15 32]


In [22]:
ranarr.shape

(10,)

In [23]:
arra.shape

(25,)

In [30]:
newArray = arra.reshape(5,5)

In [28]:
newArray.shape

(5, 5)

In [33]:
arr2 = np.resize(ranarr,(5,5))
arr2

array([[37, 23,  4, 33,  5],
       [21, 10, 47, 15, 32],
       [37, 23,  4, 33,  5],
       [21, 10, 47, 15, 32],
       [37, 23,  4, 33,  5]])

In [34]:
array  = np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arrShape = array.reshape(5,5)
arrShape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arrSize = np.resize(array,(5,5))
arrSize

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arrShape[1,2]

7

In [44]:
arrSize[3,2]

17

In [48]:
arrShape[1,2] =99


In [49]:
print("array:",array)
print("arrShape:",arrShape)

array: [ 0  1  2  3  4  5  6 99  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
arrShape: [[ 0  1  2  3  4]
 [ 5  6 99  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
arrSize[3,2] = 77
print("arrSize:",arrSize)
print("array:",array)

arrSize: [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  77  18 100]
 [ 20  21  22  23  24]]
array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [52]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 8,  5, 15, 28,  2, 19, 35, 18, 25,  2])

In [53]:
ranarr.max()

35

In [54]:
ranarr.min()

2

In [55]:
ranarr.argmax()

6

In [56]:
ranarr.argmin()

4

在NumPy中，可以使用不同的數據類型（dtype）來表示陣列中的元素。以下是一些常見的dtype類型：

1. **int**：整數，可以是int8、int16、int32、int64等不同大小的整數。
2. **uint**：無符號整數，可以是uint8、uint16、uint32、uint64等不同大小的無符號整數。
3. **float**：浮點數，可以是float16、float32、float64等不同精度的浮點數。
4. **complex**：複數，可以是complex64、complex128等不同精度的複數。
5. **bool**：布爾值，表示True或False。
6. **object**：Python對象，可以是任何Python對象。
7. **string_**：字串，固定大小的字串。
8. **unicode_**：Unicode字串，固定大小的Unicode字串。

除了以上列出的類型外，還有其他一些特殊的類型，這取決於具體的應用場景和需要。您可以通過使用`np.dtype`類來創建自定義的dtype，以滿足特定的數據需求。

In [60]:
import numpy as np
arry = np.array([1.2,3.4,5.6])
print(arry,arry.dtype)
arry2 = arry.astype(np.int8)
print(arry2,arry2.dtype)

[1.2 3.4 5.6] float64
[1 3 5] int8


In [65]:
arr = np.arange(2,15)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
arr[8]

10

In [68]:
arr[-2]

13

In [69]:
arr[1:5]

array([3, 4, 5, 6])

In [70]:
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [71]:
arr = np.arange(1,15)
arrCopy = arr.copy()
print(arr,arrCopy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [72]:
arrCopy[0] = 100
print(arr,arrCopy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] [100   2   3   4   5   6   7   8   9  10  11  12  13  14]


In [74]:
arrCopy2 = arr[:]
print(arr,arrCopy2)
arrCopy2[0] = 99
print(arr,arrCopy2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14] [99  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [77]:
myList = list(range(1,21))
print(myList)
newList = myList[:]
print(newList)
newList[1] = 100
print("="*10)
print(newList)
print(myList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 100, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [78]:
import numpy as np
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [79]:
arr_2d[1]

array([20, 25, 30])

In [81]:
arr_2d[1,0]

20

In [82]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [83]:
arr_2d[2,1:]

array([40, 45])

In [84]:
arr_2d[0:2,1]

array([10, 25])

## 條件選擇

這是一個非常基礎的概念，稍後將直接應用於 pandas，請確保你理解這部分！

我們來簡要介紹如何使用括號進行基於比較運算符的選擇。

In [85]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr > 4]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[(arr > 4) & (arr < 8)]

array([5, 6, 7])

## 算術運算

你可以輕鬆地進行*陣列與陣列*的算術運算，或者*標量與陣列*的算術運算。讓我們來看一些例子：

In [95]:
import numpy as np
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [99]:
arr / arr

C:\Users\xvpow\AppData\Local\Temp\ipykernel_14976\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## 通用陣列函數

NumPy 提供了許多[通用陣列函數](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)，或稱為 <em>ufuncs</em>（universal functions），它們本質上是可以應用於整個陣列的數學運算。讓我們來展示一些常見的通用函數：

1. **np.add** - 對陣列中的元素進行加法運算。
2. **np.subtract** - 對陣列中的元素進行減法運算。
3. **np.multiply** - 對陣列中的元素進行乘法運算。
4. **np.divide** - 對陣列中的元素進行除法運算。
5. **np.sqrt** - 計算陣列中每個元素的平方根。
6. **np.exp** - 計算 e 的指數，應用於陣列中的每個元素。
7. **np.log** - 計算陣列中每個元素的自然對數。
8. **np.sin**, **np.cos**, **np.tan** - 分別計算陣列中元素的正弦、餘弦和正切值。

這些函數可以對整個陣列進行快速和有效的元素級運算，使得數據處理更加方便和高效。

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
np.log(arr)

C:\Users\xvpow\AppData\Local\Temp\ipykernel_14976\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [104]:
arr = np.arange(1,13)
arr_2d = arr.reshape(3,4)


In [105]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d[0][0] + arr_2d[1][0] +arr_2d[2][0]

15

In [108]:
arr_2d[0][1] + arr_2d[1][1] +arr_2d[2][1]

18

In [109]:
arr_2d[0][2] + arr_2d[1][2] +arr_2d[2][2]

21

In [110]:
arr_2d[0][3] + arr_2d[1][3] +arr_2d[2][3]

24

In [111]:
arr_2d.sum()

78

In [113]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [114]:
arr_2d.sum(axis=1)

array([10, 26, 42])

## 創建一個包含10個零的陣列
```python
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

In [115]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 創建一個包含10個1的陣列

```python
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

```

In [117]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## 產生10個5的陣列

```python
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

```

In [118]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

##  要創建一個3x3矩陣，其中包含從0到8的值
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```
## 要創建一個3x3的單位矩陣（identity matrix）
```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```