In [11]:
print("Hello!")

Hello!


In [12]:
import numpy as np
my_list = [1,2,3]
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(2,16,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((3,3)) *2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random 
NumPy也有許多方法來創建隨機數陣列：

### rand
創建一個給定形狀的陣列，並用來自於[0, 1)的均勻分布的隨機樣本填充它。[[參考資料](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [31]:
np.random.rand(3)

array([0.41228301, 0.61091232, 0.95258791])

In [35]:
np.random.rand(5,5)

array([[0.19610989, 0.11758887, 0.32150717, 0.9293751 , 0.01441361],
       [0.36592792, 0.05585879, 0.12897742, 0.48633059, 0.03999111],
       [0.28323751, 0.45227391, 0.43573602, 0.65532784, 0.30083827],
       [0.79359705, 0.50572065, 0.08306736, 0.27978363, 0.11518459],
       [0.62504893, 0.15753096, 0.65592746, 0.01074207, 0.31640202]])

### randn

從“標準正態”分佈[σ = 1]返回樣本（或樣本）。與 **rand** 不同，靠近零的值更有可能出現。[[參考資料](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


標準正態分佈是一種特殊的常態分佈，其平均數（μ）為0，標準差（σ）為1。在標準正態分佈中，數據點主要集中在平均值附近，並且隨著距離平均值的增加而呈指數下降。這種分佈的曲線形狀呈鐘形，並且在平均值附近有一個尖峰。

在機器學習和統計學中，標準正態分佈通常用於建模和分析，並且在許多算法和技術中被廣泛應用。

In [39]:
nNp = np.random.randn(1000)
#print(nNp)
print(nNp.mean())
print(nNp.std())

0.0038803860234811207
1.0241336011814848


### randint
從`low`（包含）到`high`（不包含）返回隨機整數。 [[參考資料](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)]

In [53]:
np.random.randint(1,100)

2

In [54]:
np.random.randint(1,100,20)

array([74, 93, 49, 61, 42, 42, 32, 43, 47, 45, 35, 92, 80, 93, 33,  9, 47,
       30, 83, 47])

In [60]:
v2 = np.random.choice(range(1,101),10,replace=False)
#replace=False 表示不允許重複
v2

array([39, 17, 28, 70, 76, 18, 92, 56, 65, 61])

In [65]:
arr = np.arange(1,101)
print(arr)
np.random.shuffle(arr)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 18  38  60  20  49  40  86  53  22  65   3  77  19  29  30  28  26  75
  37   8 100  21  69  27  67  94  92  78  61  79  52  13  25  84  93  10
   2  46  50  44  68   6  63  87   4  47  12  54  81  32  98  11  83   1
  31  57  62  66  56  85  24  48  97  70  59   7  43  33  64  88  45  42
  74  99  41  14  89  23  55  39  82  71  17  36   5  95  91  35  16  15
  90  73  76  34   9  51  80  96  58  72]


In [8]:
import numpy as np 
print(np.random.rand(5))
np.random.seed(42)
print(np.random.rand(5))


[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [ ]:
import numpy as np 
ran = np.random.default_rng(42)
print(ran.random(5))
print(ran.integers(1,100,10))
print(ran.shuffle([1,5,6,10]))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[53 97 73 76 72 78 51 13 84 45]


In [ ]:
# 小作業
# 1~100之間的亂數
# 1~200的List 使用shuffle 幫我打亂
# 設定seed使得每次shuffle都一樣